Don't fail on yum-complete-transaction
Summary:
In some cases, rpmdb is locked and there are not complete transactions. yum-complete-transaction fails:
```
error: rpmdb: BDB0113 Thread/process 712848/140326103091008 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages index using db5 -  (-30973)
error: cannot open Packages database in /var/lib/rpm
CRITICAL:yum.verbose.cli.yumcompletets:Yum Error: Error: rpmdb open failed
```
In this case dcrpm fails without atempt to repair DB. This diff changes this behavior. yum-complete-transaction tries to complete uncomplete transactions if possible, and if it's not, then check if DB needs to be repaired, and repair it in this case.

Reviewed By: petermblair

Differential Revision: D9419627

fbshipit-source-id: 064961aee599918d895409485924c090d8132ca7